//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteCkEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientLang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSiteCkEditor.Resources.ClientLang", typeof(ClientLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Біз туралы анықтама!.
        /// </summary>
        public static string AboutOur {
            get {
                return ResourceManager.GetString("AboutOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILKWAY негізін салушы және бірінші президенті - Юнусов Бахтияр Саидұлы (1954-2010) - профессор, араб ғалымы, Қазақстан Республикасы Жаратылыстану ғылымдары академиясының және Ресейдің педагогикалық білім беру халықаралық ғылымдар академиясының корреспондент-мүшесі, Египет Араб Республикасы Танта университетінің құрметті докторы , «Қазақстан Республикасының білім беру ісінің құрметті қызметкері», медаль иегері. Ыбырай Алтынсарин..
        /// </summary>
        public static string AboutOur1 {
            get {
                return ResourceManager.GetString("AboutOur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ХАБАРЛАНДЫРУ.
        /// </summary>
        public static string ADS {
            get {
                return ResourceManager.GetString("ADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БАРЛЫҚ ЖАҢАЛЫҚТАР.
        /// </summary>
        public static string Allnews {
            get {
                return ResourceManager.GetString("Allnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жауап.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сұрақ қою.
        /// </summary>
        public static string AskQuestion {
            get {
                return ResourceManager.GetString("AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БАЙЛАНЫС.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ынтымақтастық.
        /// </summary>
        public static string Cooperation {
            get {
                return ResourceManager.GetString("Cooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аты.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тегі.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кітапхана.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оңтүстік Қазақстан облысы, Шымкент қаласында 1988 жылы 30 наурызда дүниеге келген.
        ///
        ///Әкесі – Юнусов Бахтияр Саидұлы (1954-2010 жж.) Оңтүстік Қазақстан педагогикалық университетінің алғашқы президенті және негізін қалаушы, профессор, арабтанушы-ғалым, Ресейдегі педагогикалық ғылымдар Халықаралық Академиясының және ҚР жаратылыстану Академиясының корреспондент мүшесі, Араб республикасы Египет «Панта» университетінің құрметті докторы, «ҚР білім саласының құрметті қызметкері», Ы.Алтынсарин атындағы төсбелгісіні [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Madiyartext {
            get {
                return ResourceManager.GetString("Madiyartext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юнусов Мадияр Бахтиярұлы.
        /// </summary>
        public static string Madiyartitle {
            get {
                return ResourceManager.GetString("Madiyartitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мәзір.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Толығырак.
        /// </summary>
        public static string Moredetails {
            get {
                return ResourceManager.GetString("Moredetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЖАҢАЛЫҚТАР.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платонус.
        /// </summary>
        public static string Platonus {
            get {
                return ResourceManager.GetString("Platonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Президент блогы.
        /// </summary>
        public static string Presidentsblog {
            get {
                return ResourceManager.GetString("Presidentsblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сұрақ.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сұрақтар.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ректор блогы.
        /// </summary>
        public static string Rectorsblog {
            get {
                return ResourceManager.GetString("Rectorsblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Іздеу нәтижесі.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Іздеу.
        /// </summary>
        public static string Searcholder {
            get {
                return ResourceManager.GetString("Searcholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Әлеуметтік желілер.
        /// </summary>
        public static string social {
            get {
                return ResourceManager.GetString("social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шымкент қ. Тоқаева 27 «А» (А ғимараты)
        ///уг. Түркістан.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студенттік портал.
        /// </summary>
        public static string Studentportal {
            get {
                return ResourceManager.GetString("Studentportal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оқу процесі.
        /// </summary>
        public static string Studyingproccess {
            get {
                return ResourceManager.GetString("Studyingproccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пайдалы сілтемелер.
        /// </summary>
        public static string USEFULLINKS {
            get {
                return ResourceManager.GetString("USEFULLINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мәнді дұрыс енгізіңіз!.
        /// </summary>
        public static string ValidatePres {
            get {
                return ResourceManager.GetString("ValidatePres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жауабын күтіңіз! Жауап сіздің поштаңызға келеді.
        /// </summary>
        public static string ValidatePres1 {
            get {
                return ResourceManager.GetString("ValidatePres1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тағы да қайталаңыз!.
        /// </summary>
        public static string ValidatePresRepeat {
            get {
                return ResourceManager.GetString("ValidatePresRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Біздің сайтқа қош келдіңіз!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
